#we need the sales email?  need to ask jaki?



EMAIL_REFERRAL_SENDER_USER_NAME: "jaki@krossover.com"
EMAIL_REFERRAL_SENDER_PASSWORD: "popcorn23"
API_KEY: "d4a4d51ccccfddb1b45ac8967d43989f5a4db6efe538715b1660d8ad:"
